/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "light-goten": "#fff",
        ghostwhite: "#f8faff",
        "light-bulma1": "#000",
        "secondary-text": "#858585",
        link: "#346bd4",
        darkgray: "#999",
        dodgerblue: {
          "100": "#3f84f8",
          "200": "#3e84f8",
        },
        "light-trunks": "#999ca0",
        "light-bulma": "#231f20",
        "light-beerus-beerus": "#f2f2f2",
        gainsboro: {
          "100": "#e0e0e0",
          "200": "#d9d9d9",
        },
        gray: "rgba(0, 0, 0, 0.5)",
        "light-grey": "#b0b0b0",
        lightcoral: "#ee8484",
        khaki: "#f6dc7d",
        darkseagreen: "#98d89e",
        "light-green": "#9bdd7c",
        "light-red": "#e9a0a0",
        "field-color-darker1": "#eaeaea",
        honeydew: "#e9f9eb",
        "supportive-roshi-100": "#3cc952",
        lightsteelblue: "#a9b0e5",
        lightpink: "#eca4a4",
        burlywood: "#debf85",
        mediumaquamarine: "#7fcd93",
        "light-piccolo-piccolo": "#0e6fff",
      },
      spacing: {},
      fontFamily: {
        montserrat: "Montserrat",
        poppins: "Poppins",
        lato: "Lato",
        "paragraph-text-md-s": "Figtree",
        "avertastd-semibold": "AvertaStd-Semibold",
        "open-sans": "'Open Sans'",
      },
      borderRadius: {
        xl: "20px",
        "11xl": "30px",
        "15xl": "34px",
        "165xl": "184px",
      },
    },
    fontSize: {
      "17xl": "36px",
      lg: "18px",
      sm: "14px",
      "5xl": "24px",
      base: "16px",
      xs: "12px",
      xl: "20px",
      "3xs": "10px",
      "2xl": "21px",
      "2xs": "11px",
      inherit: "inherit",
    },
  },
  corePlugins: {
    preflight: false,
  },
};
